### ISSUE TITLE
Double check regex for each Person's information

### ISSUE THREAD

**Issue by brendanneojw** [AY2324S1-CS2103T-W16-3/tp#104]
Confirm regex for each of the Person's information

**Comment by brendanneojw** [comment]
1. Name: Alphanumeric
2. Licence Plate: Alphanumeric, up to 8 characters
4. Contact Number: Numeric, exactly 8 digits
5. Tags: Alphanumeric, no white spaces allowed
6. NRIC: 3 digits with 1 character, exactly 4 characters
7. Policy Number: Alphanumeric, up to 8 characters
8. Policy Expiry and Issue Date: Date in the format dd-mm-yyyy

**Comment by cyaoxuan** [comment]
Name: Alphanumeric, can include "/" and "@"

**Comment by cyaoxuan** [comment]
Company: Alphanumber
