### ISSUE TITLE
[PE-D][Tester A] Minor bug in help message for find command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-3/tp#151]
![image.png](https://raw.githubusercontent.com/AaronJT1/ped/main/files/142c2bad-b345-45bb-a29f-2f0d3e669bcc.png)

There should not be 2 'n/NAME' parameters and 2 'l/LICENSE PLATE' in the parameters section of the help message given. But thanks for the helpful message!

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AaronJT1/ped#3

**Comment by brendanneojw** [comment]
take away the duplicate
