### ISSUE TITLE
[PE-D][Tester E] When I input a invalid leap year date into the edit command, it accepts the value but rounds the date down to the last date of the month

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W16-3/tp#171]
## Description

This one is more of a minor bug, and I am not sure if it is intended to work as such. When i type in `edit 2 pi/29-02-2023`, the value is accepted but what is reflected in the address book is 28-02-2023. The latter is a correct date, but it is different from the one that I had inputed, which is an invalid date as 2023 is not a leap year.

I am able to repeat the same results with the dates 30-02-2023 and 31-02-2023. Perhaps you would like to flag out the incorrect date as opposed to rounding it off, as the user might have accidentally inputed a wrong Month or Year instead

## Steps to Reproduce
1. Load up application with default address book
2. Type into CLI the command: `edit 2 pi/29-02-2023`

## Expected Behaviour
Application flags out the incorrect date that has been inputed.

## Actual Behaviour
Application accepts the incorrect date in command, but rounds it off to the last day of that month. Please refer to the second entry in the addressbook, and the policy issue date field specifically.

![image.png](https://raw.githubusercontent.com/ivyy-poison/ped/main/files/e67dc607-c8ad-43ab-8807-d3d791181085.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ivyy-poison/ped#3

**Comment by brendanneojw** [comment]
Same as #182 , will be settled there
