### ISSUE TITLE
[PE-D][Tester C] Non-standard names not supported by app

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W16-3/tp#183]
I have clients called `RAJU S/O DINESHWAR` and I would like to save his name as such:
`add n/Raju S/O Dineshwar p/222 e/raju@test i/888Z l/SKK1000A a/Test`

However, this is not allowed by the app, which only allows alphanumeric names. Not supporting non-standard names might result in less functionality for users with clients with non-standard names.

I think would be good to implement this feature (or actually better to write this as a "Planned Enhancement" for actual PE).

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: conradsoon/ped#14

**Comment by brendanneojw** [comment]
Change to allow `/`

**Comment by cyaoxuan** [comment]
Not supporting non-standard names because
1. its not very common 
2. people saving contact usually wont include / in the first place (no need to save full names)
3. weird names like a//////// are now valid in the app, which gives rise unviable behaviour
