### ISSUE TITLE
[PE-D][Tester B] Overflow for long remarks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-3/tp#185]
![image.png](https://raw.githubusercontent.com/SelwynAng/ped/main/files/64d12da2-9439-474c-8f94-fa5dccc15cf9.png)

When I tried to use the `remark` command and add a long remark to the 43rd client, the remark seems to overflow in the UI and I cannot view the whole remark. It would nice to edit the UI such that I can see the whole remark.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: SelwynAng/ped#9

**Comment by brendanneojw** [comment]
Remarks are not meant to be this long.
