### ISSUE TITLE
[PE-D][Tester B] Traces of AB3 are still left in the codebase

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W16-3/tp#186]
![image.png](https://raw.githubusercontent.com/SelwynAng/ped/main/files/59b87a6a-c34b-4cc6-9578-fe08a4835c8b.png)

Traces of the AB3 references are still left in the code base. Upon entering the `clear` command to clear all entries within Insureiq, the output still states "Address book has been cleared!". It would be nice to update it such that it displays "Insureiq has been cleared!"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: SelwynAng/ped#10

**Comment by brendanneojw** [comment]
Maybe can change to `Client list has been cleared` , same for sort: `Client list has been sorted` .
