### ISSUE TITLE
Modify find command to handle all kinds of exceptions that could occur

### ISSUE THREAD

**Issue by brendanneojw** [AY2324S1-CS2103T-W16-3/tp#66]
As a beginner user I can search for a specific car owner by their profile details, so that I can quickly access their information.

The application should give me an error for the following exceptions:
1. Format error in any field: `Error: Please adhere to the format for the fields`
2. No field given: `Error: Please give at least one field`
3. Field flag given but no value: `Error: Please give a value in the field(s) indicated`

Naming of the output are just examples

**Comment by cyaoxuan** [comment]
Currently implemented:
- No arguments provided (e.g. `find`): `Invalid command format!...`
- Duplicate prefixes: `Multiple values specified for the following single-valued field(s):`

To be added:
- No valid field flag provided (e.g. `find a`): `Invalid command format!...`
- Field flag given but no value: `Error: No value detected for the following field(s): `
